---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "alpine-pod"
  replicas: 5
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "alpine-pod"
    spec:
      containers:
        - name: alpine-img
          image: alpine:latest
          command: ['tail', '-f', '/dev/null']
metadata:
  name: alpine-pod
  namespace: nsm-system
  annotations:
    ns.networkservicemesh.io: icmp-responder?app=icmp
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: icmp-responder-nsc
#   annotations:
#     ns.networkservicemesh.io: icmp-responder