---
- name: Set facts
  set_fact: "orientdb_path=/opt/orientdb-{{ orientdb_version }}"

- name: Create OrientDB group
  group:
    name: orientdb
    state: present

- name: Create OrientDB user
  user:
    name: orientdb
    group: orientdb
    home: "{{ orientdb_path }}"

- name: Set execute bit on OrientDB home directory
  file:
    path: "{{ orientdb_path }}"
    state: directory
    mode: 0711

- name: Extract OrientDB
  unarchive:
    remote_src: yes
    src: "https://s3.us-east-2.amazonaws.com/orientdb3/releases/{{ orientdb_version }}/orientdb-{{ orientdb_version }}.tar.gz"
    dest: /opt
    group: orientdb
    owner: orientdb

- name: Create symlink
  file:
    src: "{{ orientdb_path }}"
    dest: /opt/orientdb
    owner: orientdb
    group: orientdb
    state: link

- name: Copy systemd unit file
  copy:
    src: "{{ orientdb_path }}/bin/orientdb.service"
    dest: /etc/systemd/system

- name: Replace user in systemd unit file
  replace:
    path: /etc/systemd/system/orientdb.service
    regexp: ORIENTDB_USER
    replace: orientdb

- name: Replace group in systemd unit file
  replace:
    path: /etc/systemd/system/orientdb.service
    regexp: ORIENTDB_GROUP
    replace: orientdb

- name: Replace user in systemd unit file
  replace:
    path: /etc/systemd/system/orientdb.service
    regexp: '\$ORIENTDB_HOME'
    replace: "{{ orientdb_path }}"

- name: Add environment to systemd unit file
  lineinfile:
    path: /etc/systemd/system/orientdb.service
    line: "Environment=ORIENTDB_ROOT_PASSWORD={{ orientdb_root_password }}"

- name: Refresh systemd cache
  become: yes
  shell: systemctl daemon-reload

- name: Starts and enable OrientDB
  service:
    name: orientdb
    state: started
    enabled: yes
