---
- include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- include_tasks: runtime.yml

- include_tasks: build.yml

- include_tasks: tests.yml

- include_tasks: ci.yml
