---
- package:
    name: "{{ item }}"
    state: present
  with_items:
    - akmod-VirtualBox
    - VirtualBox
    - kernel-devel
    - "kernel-devel-{{ ansible_kernel }}"
    - kernel-headers
    - "kernel-headers-{{ ansible_kernel }}"

- shell: "akmods"
