---
- name: Create a new instance
  os_server:
    cloud: "{{ cloud }}"
    state: present
    image: "{{ image }}"
    flavor_ram: "{{ flavor_ram }}"
    name: "{{ instance_name }}"
    key_name: "{{ ssh_key }}"
    security_groups:
     - "{{ security_group }}"
    nics:
     - net-name: "{{ network }}"
    floating_ips: "{{ floating_ips | default(omit) }}"
  register: vm

- name: Add instance to the inventory
  add_host:
    name: "{{ instance_name }}"
    ansible_ssh_host: "{{ vm.openstack.public_v4 }}"
    ansible_ssh_user: "{{ cloud_user }}"
    ansible_python_interpreter: "{{ python_interpreter }}"
    public_ip: "{{ vm.openstack.public_v4 }}"
    private_ip: "{{ vm.openstack.private_v4 }}"
    groups: "{{ host_group }}"

- name: Wait for SSH to be available
  local_action:
    module: wait_for
    host: "{{ vm.openstack.public_v4 }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
