---
- name: Copy skydive binary
  copy:
    src: "{{ skydive_binary_remote_location | replace('file://', '') }}"
    dest: "{{ skydive_binary_location }}"
    force: true
    mode: 0755
  when: '"file://" in skydive_binary_remote_location'

- name: Download skydive binary
  get_url:
    url: "{{ skydive_binary_remote_location }}"
    dest: "{{ skydive_binary_location }}"
    force: true
    mode: 0755
  when: '"file://" not in skydive_binary_remote_location'
