---
- name: Generate systemd unit file
  become: yes
  template:
    src: "{{ role_path }}/templates/skydive.service.j2"
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: Start service
  systemd:
    name: "{{ service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Check Skydive service started
  command: systemctl status {{ service_name }}
  ignore_errors: yes
  changed_when: false
  register: service_skydive_status

- name: Report status of Skydive service
  fail:
    msg: |
      Service {{ service_name }} is not running.
      {{ service_skydive_status.stdout }}
      {{ service_skydive_status.stderr }}
  when: service_skydive_status is failed
