// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flow/layers/vrrpv2.proto

package layers // import "github.com/skydive-project/skydive/flow/layers"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// LayerVRRPv2 wrapper to generate extra layer
type VRRPv2 struct {
	Contents     []byte `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	Payload      []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Version      uint8  `protobuf:"varint,3,opt,name=version,proto3,casttype=uint8" json:"version,omitempty"`
	VirtualRtrID uint8  `protobuf:"varint,4,opt,name=virtual_rtr_id,json=virtualRtrId,proto3,casttype=uint8" json:"VirtualRtrID,omitempty"`
	Priority     uint8  `protobuf:"varint,5,opt,name=priority,proto3,casttype=uint8" json:"priority,omitempty"`
	CountIPAddr  uint8  `protobuf:"varint,6,opt,name=count_ipaddr,json=countIpaddr,proto3,casttype=uint8" json:"CountIPAddr,omitempty"`
	AdverInt     uint8  `protobuf:"varint,7,opt,name=adver_int,json=adverInt,proto3,casttype=uint8" json:"adver_int,omitempty"`
	Checksum     uint16 `protobuf:"varint,8,opt,name=checksum,proto3,casttype=uint16" json:"checksum,omitempty"`
}

func (m *VRRPv2) Reset()         { *m = VRRPv2{} }
func (m *VRRPv2) String() string { return proto.CompactTextString(m) }
func (*VRRPv2) ProtoMessage()    {}
func (*VRRPv2) Descriptor() ([]byte, []int) {
	return fileDescriptor_vrrpv2_eac26bf9ec52bbc8, []int{0}
}
func (m *VRRPv2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VRRPv2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VRRPv2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *VRRPv2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VRRPv2.Merge(dst, src)
}
func (m *VRRPv2) XXX_Size() int {
	return m.ProtoSize()
}
func (m *VRRPv2) XXX_DiscardUnknown() {
	xxx_messageInfo_VRRPv2.DiscardUnknown(m)
}

var xxx_messageInfo_VRRPv2 proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VRRPv2)(nil), "layers.VRRPv2")
}
func (m *VRRPv2) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VRRPv2) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Contents) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(len(m.Contents)))
		i += copy(dAtA[i:], m.Contents)
	}
	if len(m.Payload) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(len(m.Payload)))
		i += copy(dAtA[i:], m.Payload)
	}
	if m.Version != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(m.Version))
	}
	if m.VirtualRtrID != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(m.VirtualRtrID))
	}
	if m.Priority != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(m.Priority))
	}
	if m.CountIPAddr != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(m.CountIPAddr))
	}
	if m.AdverInt != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(m.AdverInt))
	}
	if m.Checksum != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintVrrpv2(dAtA, i, uint64(m.Checksum))
	}
	return i, nil
}

func encodeVarintVrrpv2(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *VRRPv2) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Contents)
	if l > 0 {
		n += 1 + l + sovVrrpv2(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovVrrpv2(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovVrrpv2(uint64(m.Version))
	}
	if m.VirtualRtrID != 0 {
		n += 1 + sovVrrpv2(uint64(m.VirtualRtrID))
	}
	if m.Priority != 0 {
		n += 1 + sovVrrpv2(uint64(m.Priority))
	}
	if m.CountIPAddr != 0 {
		n += 1 + sovVrrpv2(uint64(m.CountIPAddr))
	}
	if m.AdverInt != 0 {
		n += 1 + sovVrrpv2(uint64(m.AdverInt))
	}
	if m.Checksum != 0 {
		n += 1 + sovVrrpv2(uint64(m.Checksum))
	}
	return n
}

func sovVrrpv2(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozVrrpv2(x uint64) (n int) {
	return sovVrrpv2(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VRRPv2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrrpv2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VRRPv2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VRRPv2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contents", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrrpv2
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contents = append(m.Contents[:0], dAtA[iNdEx:postIndex]...)
			if m.Contents == nil {
				m.Contents = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrrpv2
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= (uint8(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualRtrID", wireType)
			}
			m.VirtualRtrID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VirtualRtrID |= (uint8(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= (uint8(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountIPAddr", wireType)
			}
			m.CountIPAddr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountIPAddr |= (uint8(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdverInt", wireType)
			}
			m.AdverInt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AdverInt |= (uint8(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			m.Checksum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Checksum |= (uint16(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVrrpv2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVrrpv2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVrrpv2(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVrrpv2
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVrrpv2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthVrrpv2
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowVrrpv2
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipVrrpv2(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthVrrpv2 = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVrrpv2   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("flow/layers/vrrpv2.proto", fileDescriptor_vrrpv2_eac26bf9ec52bbc8) }

var fileDescriptor_vrrpv2_eac26bf9ec52bbc8 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x13, 0x77, 0x37, 0xcd, 0xce, 0x46, 0x0f, 0x03, 0xca, 0xb0, 0x87, 0x64, 0x51, 0x5c,
	0x7a, 0xb0, 0x0d, 0x6d, 0x41, 0xc4, 0x9b, 0xd5, 0x4b, 0xc0, 0x43, 0x09, 0x52, 0xd0, 0x4b, 0x48,
	0x33, 0xd3, 0x76, 0x6c, 0x92, 0x09, 0x93, 0xc9, 0x48, 0xde, 0xc0, 0xa3, 0xbe, 0x41, 0x1f, 0xc7,
	0x63, 0x8f, 0x9e, 0x82, 0x24, 0xb7, 0x3e, 0x42, 0x4f, 0xd2, 0x29, 0x6d, 0x83, 0xee, 0x6d, 0x7e,
	0xdf, 0xef, 0x3f, 0xdf, 0x37, 0xf0, 0x0d, 0x40, 0xf3, 0x98, 0x7d, 0x73, 0xe3, 0xb0, 0x24, 0x3c,
	0x77, 0x25, 0xe7, 0x99, 0x1c, 0xf6, 0x33, 0xce, 0x04, 0x83, 0xc6, 0xa1, 0x78, 0xdb, 0x5b, 0x50,
	0xb1, 0x2c, 0x66, 0xfd, 0x88, 0x25, 0xee, 0x82, 0x2d, 0x98, 0xab, 0xf4, 0xac, 0x98, 0x2b, 0x52,
	0xa0, 0x4e, 0x87, 0x6b, 0xcf, 0x7f, 0x5e, 0x00, 0x63, 0xea, 0xfb, 0x13, 0x39, 0x84, 0xb7, 0xc0,
	0x8c, 0x58, 0x2a, 0x48, 0x2a, 0x72, 0xa4, 0xdf, 0xe9, 0x5d, 0xcb, 0x3f, 0x31, 0x44, 0xa0, 0x93,
	0x85, 0x65, 0xcc, 0x42, 0x8c, 0x1e, 0x29, 0x75, 0x44, 0xf8, 0x02, 0x74, 0x24, 0xe1, 0x39, 0x65,
	0x29, 0xba, 0xb8, 0xd3, 0xbb, 0x8f, 0xc7, 0xd7, 0xbb, 0xca, 0xb9, 0x2a, 0x68, 0x2a, 0xde, 0xf8,
	0x47, 0x03, 0x3f, 0x83, 0x27, 0x92, 0x72, 0x51, 0x84, 0x71, 0xc0, 0x05, 0x0f, 0x28, 0x46, 0x97,
	0x2a, 0x3b, 0xaa, 0x2b, 0xc7, 0x9a, 0x1e, 0x8c, 0x2f, 0xb8, 0xf7, 0x61, 0x5b, 0x39, 0xcf, 0xda,
	0xfc, 0x8a, 0x25, 0x54, 0x90, 0x24, 0x13, 0xe5, 0xb9, 0xab, 0x25, 0xcf, 0x01, 0x0c, 0x5f, 0x02,
	0x33, 0xe3, 0x94, 0x71, 0x2a, 0x4a, 0x74, 0xf5, 0xef, 0x03, 0x4e, 0x0a, 0x7e, 0x02, 0x56, 0xc4,
	0x8a, 0x54, 0x04, 0x34, 0x0b, 0x31, 0xe6, 0xc8, 0x50, 0xd1, 0x41, 0x5d, 0x39, 0x37, 0xef, 0xf7,
	0x75, 0x6f, 0xf2, 0x0e, 0x63, 0xbe, 0xad, 0x9c, 0xa7, 0x2d, 0x7c, 0x68, 0xfa, 0x8d, 0x6a, 0xe3,
	0xa9, 0x2e, 0xf0, 0x1e, 0x5c, 0x87, 0x58, 0x12, 0x1e, 0xd0, 0x54, 0xa0, 0xce, 0x7f, 0xd3, 0x95,
	0xf3, 0x52, 0x01, 0xef, 0x81, 0x19, 0x2d, 0x49, 0xb4, 0xca, 0x8b, 0x04, 0x99, 0x2a, 0x06, 0x76,
	0x95, 0x63, 0xec, 0x63, 0x83, 0xd7, 0xfe, 0xc9, 0xbd, 0xbd, 0xfc, 0xbe, 0x76, 0xb4, 0xf1, 0xc7,
	0x5f, 0xb5, 0xad, 0x6f, 0x6a, 0x5b, 0xff, 0x53, 0xdb, 0xda, 0x8f, 0xc6, 0xd6, 0xd6, 0x8d, 0xad,
	0x6f, 0x1a, 0x5b, 0xfb, 0xdd, 0xd8, 0xda, 0x97, 0x7e, 0x6b, 0xc1, 0xf9, 0xaa, 0xc4, 0x54, 0x92,
	0x5e, 0xc6, 0xd9, 0x57, 0x12, 0x89, 0x23, 0xbb, 0xad, 0x5f, 0x32, 0x33, 0xd4, 0xa2, 0x47, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x4d, 0xd4, 0x52, 0x3b, 0x02, 0x00, 0x00,
}
