---
flavor_ram: 4096
instance_name: myvm
image: Fedora 25 x86_64
# image: CentOS 7 (1603) x86_64
ssh_key: Bob
network: SkyNet
cloud: rcip-dev
# cloud_user: fedora
cloud_user: centos
python_interpreter: /usr/bin/python3
security_group: default
