// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nsmd.proto

package nsmdapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ConnectionRequest is sent by a NSM client to build a connection with NSM.
type ClientConnectionRequest struct {
	Workspace            string   `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConnectionRequest) Reset()         { *m = ClientConnectionRequest{} }
func (m *ClientConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ClientConnectionRequest) ProtoMessage()    {}
func (*ClientConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmd_a586b2a60b7b2017, []int{0}
}
func (m *ClientConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConnectionRequest.Unmarshal(m, b)
}
func (m *ClientConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *ClientConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnectionRequest.Merge(dst, src)
}
func (m *ClientConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ClientConnectionRequest.Size(m)
}
func (m *ClientConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnectionRequest proto.InternalMessageInfo

func (m *ClientConnectionRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

// ClientConnectionReply is sent back by NSM as a reply to ClientConnectionRequest
// accepted true will indicate that the connection is accepted, otherwise false
// indicates that connection was refused and admission_error will provide details
// why connection was refused.
type ClientConnectionReply struct {
	Workspace            string   `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	HostBasedir          string   `protobuf:"bytes,2,opt,name=hostBasedir,proto3" json:"hostBasedir,omitempty"`
	ClientBaseDir        string   `protobuf:"bytes,3,opt,name=clientBaseDir,proto3" json:"clientBaseDir,omitempty"`
	NsmServerSocket      string   `protobuf:"bytes,4,opt,name=nsmServerSocket,proto3" json:"nsmServerSocket,omitempty"`
	NsmClientSocket      string   `protobuf:"bytes,5,opt,name=nsmClientSocket,proto3" json:"nsmClientSocket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConnectionReply) Reset()         { *m = ClientConnectionReply{} }
func (m *ClientConnectionReply) String() string { return proto.CompactTextString(m) }
func (*ClientConnectionReply) ProtoMessage()    {}
func (*ClientConnectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmd_a586b2a60b7b2017, []int{1}
}
func (m *ClientConnectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConnectionReply.Unmarshal(m, b)
}
func (m *ClientConnectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConnectionReply.Marshal(b, m, deterministic)
}
func (dst *ClientConnectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnectionReply.Merge(dst, src)
}
func (m *ClientConnectionReply) XXX_Size() int {
	return xxx_messageInfo_ClientConnectionReply.Size(m)
}
func (m *ClientConnectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnectionReply proto.InternalMessageInfo

func (m *ClientConnectionReply) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *ClientConnectionReply) GetHostBasedir() string {
	if m != nil {
		return m.HostBasedir
	}
	return ""
}

func (m *ClientConnectionReply) GetClientBaseDir() string {
	if m != nil {
		return m.ClientBaseDir
	}
	return ""
}

func (m *ClientConnectionReply) GetNsmServerSocket() string {
	if m != nil {
		return m.NsmServerSocket
	}
	return ""
}

func (m *ClientConnectionReply) GetNsmClientSocket() string {
	if m != nil {
		return m.NsmClientSocket
	}
	return ""
}

// DeleteConnectionRequest is sent by a nsm-k8s to delete connection with a client.
type DeleteConnectionRequest struct {
	Workspace            string   `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConnectionRequest) Reset()         { *m = DeleteConnectionRequest{} }
func (m *DeleteConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteConnectionRequest) ProtoMessage()    {}
func (*DeleteConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmd_a586b2a60b7b2017, []int{2}
}
func (m *DeleteConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConnectionRequest.Unmarshal(m, b)
}
func (m *DeleteConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConnectionRequest.Merge(dst, src)
}
func (m *DeleteConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteConnectionRequest.Size(m)
}
func (m *DeleteConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConnectionRequest proto.InternalMessageInfo

func (m *DeleteConnectionRequest) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

type DeleteConnectionReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConnectionReply) Reset()         { *m = DeleteConnectionReply{} }
func (m *DeleteConnectionReply) String() string { return proto.CompactTextString(m) }
func (*DeleteConnectionReply) ProtoMessage()    {}
func (*DeleteConnectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmd_a586b2a60b7b2017, []int{3}
}
func (m *DeleteConnectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConnectionReply.Unmarshal(m, b)
}
func (m *DeleteConnectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConnectionReply.Marshal(b, m, deterministic)
}
func (dst *DeleteConnectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConnectionReply.Merge(dst, src)
}
func (m *DeleteConnectionReply) XXX_Size() int {
	return xxx_messageInfo_DeleteConnectionReply.Size(m)
}
func (m *DeleteConnectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConnectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConnectionReply proto.InternalMessageInfo

type EnumConnectionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumConnectionRequest) Reset()         { *m = EnumConnectionRequest{} }
func (m *EnumConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*EnumConnectionRequest) ProtoMessage()    {}
func (*EnumConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmd_a586b2a60b7b2017, []int{4}
}
func (m *EnumConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumConnectionRequest.Unmarshal(m, b)
}
func (m *EnumConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *EnumConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumConnectionRequest.Merge(dst, src)
}
func (m *EnumConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_EnumConnectionRequest.Size(m)
}
func (m *EnumConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnumConnectionRequest proto.InternalMessageInfo

type EnumConnectionReply struct {
	Workspace            []string `protobuf:"bytes,1,rep,name=workspace,proto3" json:"workspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumConnectionReply) Reset()         { *m = EnumConnectionReply{} }
func (m *EnumConnectionReply) String() string { return proto.CompactTextString(m) }
func (*EnumConnectionReply) ProtoMessage()    {}
func (*EnumConnectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmd_a586b2a60b7b2017, []int{5}
}
func (m *EnumConnectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumConnectionReply.Unmarshal(m, b)
}
func (m *EnumConnectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumConnectionReply.Marshal(b, m, deterministic)
}
func (dst *EnumConnectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumConnectionReply.Merge(dst, src)
}
func (m *EnumConnectionReply) XXX_Size() int {
	return xxx_messageInfo_EnumConnectionReply.Size(m)
}
func (m *EnumConnectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumConnectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_EnumConnectionReply proto.InternalMessageInfo

func (m *EnumConnectionReply) GetWorkspace() []string {
	if m != nil {
		return m.Workspace
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientConnectionRequest)(nil), "nsmdapi.ClientConnectionRequest")
	proto.RegisterType((*ClientConnectionReply)(nil), "nsmdapi.ClientConnectionReply")
	proto.RegisterType((*DeleteConnectionRequest)(nil), "nsmdapi.DeleteConnectionRequest")
	proto.RegisterType((*DeleteConnectionReply)(nil), "nsmdapi.DeleteConnectionReply")
	proto.RegisterType((*EnumConnectionRequest)(nil), "nsmdapi.EnumConnectionRequest")
	proto.RegisterType((*EnumConnectionReply)(nil), "nsmdapi.EnumConnectionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NSMDClient is the client API for NSMD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NSMDClient interface {
	RequestClientConnection(ctx context.Context, in *ClientConnectionRequest, opts ...grpc.CallOption) (*ClientConnectionReply, error)
	EnumConnection(ctx context.Context, in *EnumConnectionRequest, opts ...grpc.CallOption) (*EnumConnectionReply, error)
	DeleteClientConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionReply, error)
}

type nSMDClient struct {
	cc *grpc.ClientConn
}

func NewNSMDClient(cc *grpc.ClientConn) NSMDClient {
	return &nSMDClient{cc}
}

func (c *nSMDClient) RequestClientConnection(ctx context.Context, in *ClientConnectionRequest, opts ...grpc.CallOption) (*ClientConnectionReply, error) {
	out := new(ClientConnectionReply)
	err := c.cc.Invoke(ctx, "/nsmdapi.NSMD/RequestClientConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSMDClient) EnumConnection(ctx context.Context, in *EnumConnectionRequest, opts ...grpc.CallOption) (*EnumConnectionReply, error) {
	out := new(EnumConnectionReply)
	err := c.cc.Invoke(ctx, "/nsmdapi.NSMD/EnumConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSMDClient) DeleteClientConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionReply, error) {
	out := new(DeleteConnectionReply)
	err := c.cc.Invoke(ctx, "/nsmdapi.NSMD/DeleteClientConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NSMDServer is the server API for NSMD service.
type NSMDServer interface {
	RequestClientConnection(context.Context, *ClientConnectionRequest) (*ClientConnectionReply, error)
	EnumConnection(context.Context, *EnumConnectionRequest) (*EnumConnectionReply, error)
	DeleteClientConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionReply, error)
}

func RegisterNSMDServer(s *grpc.Server, srv NSMDServer) {
	s.RegisterService(&_NSMD_serviceDesc, srv)
}

func _NSMD_RequestClientConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSMDServer).RequestClientConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsmdapi.NSMD/RequestClientConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSMDServer).RequestClientConnection(ctx, req.(*ClientConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSMD_EnumConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSMDServer).EnumConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsmdapi.NSMD/EnumConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSMDServer).EnumConnection(ctx, req.(*EnumConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSMD_DeleteClientConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSMDServer).DeleteClientConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsmdapi.NSMD/DeleteClientConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSMDServer).DeleteClientConnection(ctx, req.(*DeleteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NSMD_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nsmdapi.NSMD",
	HandlerType: (*NSMDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestClientConnection",
			Handler:    _NSMD_RequestClientConnection_Handler,
		},
		{
			MethodName: "EnumConnection",
			Handler:    _NSMD_EnumConnection_Handler,
		},
		{
			MethodName: "DeleteClientConnection",
			Handler:    _NSMD_DeleteClientConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nsmd.proto",
}

func init() { proto.RegisterFile("nsmd.proto", fileDescriptor_nsmd_a586b2a60b7b2017) }

var fileDescriptor_nsmd_a586b2a60b7b2017 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2b, 0xce, 0x4d,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0xb1, 0x13, 0x0b, 0x32, 0x95, 0xcc, 0xb9,
	0xc4, 0x9d, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x9c, 0xf3, 0xf3, 0xf2, 0x52, 0x93, 0x4b, 0x32, 0xf3,
	0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0xcb, 0xf3, 0x8b, 0xb2,
	0x8b, 0x0b, 0x12, 0x93, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x4a, 0x17,
	0x19, 0xb9, 0x44, 0x31, 0x75, 0x16, 0xe4, 0x54, 0xe2, 0xd7, 0x27, 0xa4, 0xc0, 0xc5, 0x9d, 0x91,
	0x5f, 0x5c, 0xe2, 0x94, 0x58, 0x9c, 0x9a, 0x92, 0x59, 0x24, 0xc1, 0x04, 0x96, 0x47, 0x16, 0x12,
	0x52, 0xe1, 0xe2, 0x4d, 0x06, 0x1b, 0x0c, 0x12, 0x70, 0x01, 0xaa, 0x61, 0x06, 0xab, 0x41, 0x15,
	0x14, 0xd2, 0xe0, 0xe2, 0x07, 0xfa, 0x21, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0x28, 0x38, 0x3f, 0x39,
	0x3b, 0xb5, 0x44, 0x82, 0x05, 0xac, 0x0e, 0x5d, 0x18, 0xaa, 0x12, 0xe2, 0x56, 0xa8, 0x4a, 0x56,
	0xb8, 0x4a, 0x64, 0x61, 0x50, 0x60, 0xb8, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0x92, 0x1a, 0x18, 0xe2,
	0x5c, 0xa2, 0x98, 0x1a, 0x81, 0x61, 0x01, 0x92, 0x70, 0xcd, 0x2b, 0xcd, 0xc5, 0x30, 0x4f, 0xc9,
	0x98, 0x4b, 0x18, 0x5d, 0x02, 0x4b, 0xd8, 0x31, 0xa3, 0x58, 0x63, 0xd4, 0xcf, 0xc4, 0xc5, 0xe2,
	0x17, 0xec, 0xeb, 0x22, 0x14, 0xcd, 0x25, 0x0e, 0x35, 0x08, 0x3d, 0x0a, 0x84, 0x14, 0xf4, 0xa0,
	0x51, 0xab, 0x87, 0x23, 0x5e, 0xa5, 0xe4, 0xf0, 0xa8, 0x00, 0xb9, 0xc1, 0x8f, 0x8b, 0x0f, 0xd5,
	0x69, 0x42, 0x08, 0x1d, 0x58, 0x3d, 0x23, 0x25, 0x83, 0x53, 0x1e, 0x64, 0x5e, 0x14, 0x97, 0x18,
	0x34, 0x70, 0x70, 0xbb, 0x15, 0x47, 0xb0, 0x23, 0xb9, 0x15, 0x6b, 0xf8, 0x26, 0xb1, 0x81, 0x93,
	0xb3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xad, 0x32, 0x4d, 0xdc, 0x02, 0x00, 0x00,
}
