---
- name: Check API status, retrieve token from login page
  uri:
    url: "http://{{ analyzers.split(',')[0] }}/login"
    status_code: 200
    method: POST
    body: "username={{ skydive_username }}&password={{ skydive_password }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login
  until: login is not failed
  retries: 10
  delay: 20
  tags:
    - tests

- name: Check API status
  uri:
    url: "http://{{ analyzers.split(',')[0] }}/api/status"
    method: GET
    return_content: yes
    headers:
      Cookie: "{{ login.set_cookie | regex_replace(',', ';') }}"
  register: response
  changed_when: false
  until: response.json is defined and response.json.Agents is defined and (response.json.Agents|length) == (groups['agents']|length)
  retries: 10
  delay: 20
  tags:
    - tests
