---
- os_network:
    cloud: "{{ cloud }}"
    state: present
    name: "{{ network }}"
  register: os_network

- os_image:
    cloud: "{{ cloud }}"
    state: present
    name: "{{ image }}"
  register: os_image

- os_flavor_facts:
    cloud: "{{ cloud }}"
    name: "{{ flavor }}"
  register: os_flavor

- set_fact:
    os_network: "{{ os_network.id }}"
    os_flavor: "{{ os_flavor.ansible_facts.openstack_flavors[0].id }}"
    os_image: "{{ os_image.id }}"

- os_security_group:
    cloud: "{{ cloud }}"
    state: present
    name: jenkins
    description: security group for Jenkins master

- os_security_group_rule:
    cloud: "{{ cloud }}"
    security_group: jenkins
    protocol: tcp
    state: present
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- os_security_group_rule:
    cloud: "{{ cloud }}"
    security_group: jenkins
    protocol: tcp
    state: present
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

- os_security_group_rule:
    cloud: "{{ cloud }}"
    security_group: jenkins
    protocol: tcp
    state: present
    port_range_min: 39553
    port_range_max: 39553
    remote_group: jenkins

- name: Create Jenkins master
  include_role:
    name: create_instances
  vars:
    instance_name: jenkins_master
    security_group: jenkins
    host_group: masters
    network: "{{ network }}"
    image: "{{ image }}"
    floating_ips:
      - "{{ jenkins_public_ip }}"

- name: Create Jenkins slaves
  include_role:
    name: create_instances
  vars:
    name: create_instances
    instance_name: "jenkins_slave-{{ item }}"
    security_group: jenkins
    host_group: slaves
  with_sequence: count={{ slave_count }}
